# fly.toml file generated for no-drones-in-the-wild on 2023-01-14T15:48:32+02:00

app = "no-drones-in-the-wild"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = 8080 #

[experimental]
  auto_rollback = true

[build]
  image = "flyio/hellofly:latest"


[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
