name: Continuous Integration

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies on back end
        run: cd /backend_birds && npm i

      - name: Install dependencies on front end
        run: cd /frontend_birds && npm i

      - name: Build the application
        run: npm run build:ui

      - name: Run tests for back end
        run: cd /backend_birds &&  npm run test

      - name: Run tests for front end
        run: cd /frontend_birds && npm run test

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm run build:full
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
